apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: tp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 192.168.8.156:5001/yohan-engineer/node-api-app:3.0.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: tp-namespace
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

